# Generated by Django 5.1.2 on 2024-12-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ask", "0002_alter_answerlike_answer_alter_questionlike_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="ask.question",
                verbose_name="Вопрос",
            ),
        ),
    ]
