# Generated by Django 5.1.2 on 2024-12-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ask", "0005_alter_profile_avatar_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                help_text="Размер до 10МБ",
                upload_to="avatars/",
                verbose_name="Картинка профиля",
            ),
        ),
    ]
