# Generated by Django 5.1.2 on 2024-12-25 13:13

import ask.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ask", "0006_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                help_text="Размер до 10МБ",
                upload_to=ask.models.handle_upload_to,
                verbose_name="Картинка профиля",
            ),
        ),
    ]
